trigger: none

resources:
  repositories:
    - repository: voip
      type: git
      name: 31963-voip-mt
    - repository: nonvoip
      type: git
      name: 31963-non-voip-mt
    - repository: shared
      type: git
      name: 31963-common-modules

stages:
  - stage: VOIP_MT
    displayName: VOIP Infra
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/mtns/automation'))
    jobs:
      - template: templates/main-infra-template.yml@shared
        parameters:
          region: 'eastus2'
          environment: 'nprd'
          repoName: '31963-voip-mt'
          runStorage: true
          runPlan: true
          runApply: true

  - stage: NONVOIP_MT
    displayName: Non-VOIP Infra
    condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/mtns/automation'))
    jobs:
      - template: templates/main-infra-template.yml@shared
        parameters:
          region: 'westus2'
          environment: 'prod'
          repoName: '31963-non-voip-mt'
          runStorage: false
          runPlan: true
          runApply: true
