parameters:
  - name: region
    type: string
  - name: environment
    type: string
  - name: repoName
    type: string
  - name: runStorage
    type: boolean
    default: true
  - name: runPlan
    type: boolean
    default: true
  - name: runApply
    type: boolean
    default: true

variables:
  - ${{ if and(eq(parameters.region, 'westus2'), eq(parameters.environment, 'dev')) }}:
      - template: variables-westus2-dev.yaml
  - ${{ if and(eq(parameters.region, 'westus2'), eq(parameters.environment, 'nprd')) }}:
      - template: variables-westus2-nprd.yaml
  - ${{ if and(eq(parameters.region, 'westus2'), eq(parameters.environment, 'prod')) }}:
      - template: variables-westus2-prod.yaml

  - ${{ if and(eq(parameters.region, 'eastus2'), eq(parameters.environment, 'dev')) }}:
      - template: variables-eastus2-dev.yaml
  - ${{ if and(eq(parameters.region, 'eastus2'), eq(parameters.environment, 'nprd')) }}:
      - template: variables-eastus2-nprd.yaml
  - ${{ if and(eq(parameters.region, 'eastus2'), eq(parameters.environment, 'prod')) }}:
      - template: variables-eastus2-prod.yaml

  - ${{ if and(eq(parameters.region, 'southcentralus'), eq(parameters.environment, 'dev')) }}:
      - template: variables-southcentralus-dev.yaml
  - ${{ if and(eq(parameters.region, 'southcentralus'), eq(parameters.environment, 'nprd')) }}:
      - template: variables-southcentralus-nprd.yaml
  - ${{ if and(eq(parameters.region, 'southcentralus'), eq(parameters.environment, 'prod')) }}:
      - template: variables-southcentralus-prod.yaml

  - ${{ if and(eq(parameters.region, 'westus3'), eq(parameters.environment, 'dev')) }}:
      - template: variables-westus3-dev.yaml
  - ${{ if and(eq(parameters.region, 'westus3'), eq(parameters.environment, 'nprd')) }}:
      - template: variables-westus3-nprd.yaml
  - ${{ if and(eq(parameters.region, 'westus3'), eq(parameters.environment, 'prod')) }}:
      - template: variables-westus3-prod.yaml

  - ${{ if and(eq(parameters.region, 'westus2'), eq(parameters.environment, 'dev')) }}:
      - group: mtns-common-westus2-dev
  - ${{ if and(eq(parameters.region, 'westus2'), eq(parameters.environment, 'nprd')) }}:
      - group: mtns-common-westus2-nprd
  - ${{ if and(eq(parameters.region, 'westus2'), eq(parameters.environment, 'prod')) }}:
      - group: mtns-common-westus2-prod

  - ${{ if and(eq(parameters.region, 'eastus2'), eq(parameters.environment, 'dev')) }}:
      - group: mtns-common-eastus2-dev
  - ${{ if and(eq(parameters.region, 'eastus2'), eq(parameters.environment, 'nprd')) }}:
      - group: mtns-common-eastus2-nprd
  - ${{ if and(eq(parameters.region, 'eastus2'), eq(parameters.environment, 'prod')) }}:
      - group: mtns-common-eastus2-prod

  - ${{ if and(eq(parameters.region, 'southcentralus'), eq(parameters.environment, 'dev')) }}:
      - group: mtns-common-southcentralus-dev
  - ${{ if and(eq(parameters.region, 'southcentralus'), eq(parameters.environment, 'nprd')) }}:
      - group: mtns-common-southcentralus-nprd
  - ${{ if and(eq(parameters.region, 'southcentralus'), eq(parameters.environment, 'prod')) }}:
      - group: mtns-common-southcentralus-prod

  - ${{ if and(eq(parameters.region, 'westus3'), eq(parameters.environment, 'dev')) }}:
      - group: mtns-common-westus3-dev
  - ${{ if and(eq(parameters.region, 'westus3'), eq(parameters.environment, 'nprd')) }}:
      - group: mtns-common-westus3-nprd
  - ${{ if and(eq(parameters.region, 'westus3'), eq(parameters.environment, 'prod')) }}:
      - group: mtns-common-westus3-prod

stages:
  - ${{ if eq(parameters.runStorage, true) }}:
      - stage: SetupTerraformStorageAccount
        displayName: Setup Terraform Storage Account
        jobs:
          - job: StorageAccount
            steps:
              - checkout: ${{ parameters.repoName }}
              - script: echo "Creating storage account"

  - ${{ if eq(parameters.runPlan, true) }}:
      - stage: deploy_rg_plan
        displayName: Terraform Plan
        jobs:
          - job: plan
            steps:
              - checkout: self
              - task: qetza.replacetokens.replacetokens-task.replacetokens@3
                inputs:
                  rootDirectory: "$(System.DefaultWorkingDirectory)/config/"
                  targetFiles: "**/*.tfvars"
                  tokenPrefix: "__"
                  tokenSuffix: "__"
              - template: ../templates/terraformCmd.yaml
                parameters:
                  terraformInitDisplay: ${{ variables.terraformInitDisplay }}
                  terraformDisplay: ${{ variables.terraformDisplay }}
                  terraformCommand: plan
                  serviceConnectionApp: ${{ variables.serviceConnectionApp }}
                  sa_rg_name: ${{ variables.sa_rg_name }}
                  sa_name: ${{ variables.sa_name }}
                  sa_key: ${{ variables.sa_key }}
                  sa_container_name: ${{ variables.sa_container_name }}
                  env: ${{ variables.env }}
                  region: ${{ variables.region }}
                  resourceType: rg

  - ${{ if eq(parameters.runApply, true) }}:
      - stage: deploy_rg_apply
        displayName: Terraform Apply
        jobs:
          - job: apply
            steps:
              - checkout: self
              - task: qetza.replacetokens.replacetokens-task.replacetokens@3
                inputs:
                  rootDirectory: "$(System.DefaultWorkingDirectory)/config/"
                  targetFiles: "**/*.tfvars"
                  tokenPrefix: "__"
                  tokenSuffix: "__"
              - template: ../templates/terraformCmd.yaml
                parameters:
                  terraformInitDisplay: ${{ variables.terraformInitDisplay }}
                  terraformDisplay: ${{ variables.terraformDisplay }}
                  terraformCommand: apply
                  serviceConnectionApp: ${{ variables.serviceConnectionApp }}
                  sa_rg_name: ${{ variables.sa_rg_name }}
                  sa_name: ${{ variables.sa_name }}
                  sa_key: ${{ variables.sa_key }}
                  sa_container_name: ${{ variables.sa_container_name }}
                  env: ${{ variables.env }}
                  region: ${{ variables.region }}
                  resourceType: rg
